<?php

namespace App\http\utilities;


class city {


    protected static $cities = [
        'Abbottabad',
        'Arifwala',
        'Astore' ,
        'Attock',
        'Awaran' ,
        'Badin' ,
        'Bagh'  ,
        'Bahawalnagar',
        'Bahawalpur' ,
        'Bannu' ,
        'Bhakkar' ,
        'Bhimber' ,
        'Burewala' ,
        'Chaghi'  ,
        'Chakwal'  ,
        'Chichawatni' ,
        'Chiniot' ,
        'Chitral' ,
        'Chunian' ,
        'Dadu'  ,
        'Daska' ,
        'Depalpur' ,
        'Dera Ghazi Khan' ,
        'Dera Ismail Khan',
        'Duniya Pur' ,
        'FATA' ,
		'Faisalabad',
		'Fateh Jang',
		'Galyat',
		'Ghotki',
		'Gilgit',
		'Gujar Khan',
		'Gujranwala',
		'Gujrat',
		'Gwadar',
		'Hafizabad',
		'Haripur',
		'Haroonabad',
		'Hasan Abdal',
		'Hub (Hub Chowki)',
		'Hunza',
		'Hyderabad',
		'Islamabad',
		'Jacobabad',
		'Jauharabad',
		'Jhang',
		'Jhelum',
		'Kaghan',
		'Kalat',
		'Karachi',
		'Karak',
		'Kasur',
		'Khairpur',
		'Khanewal',
		'Kharian',
		'Khushab',
		'Khuzdar',
		'Kohat',
		'Kot Addu',
		'Kotli',
		'Lahore',
		'Lalamusa',
		'Larkana',
		'Lasbela',
		'Layyah',
		'Lodhran',
		'Loralai',
		'Mailsi',
		'Makran',
		'Malakand',
		'Mandi Bahauddin',
		'Mansehra',
		'Mardan',
		'Matiari',
		'Mian Channu',
		'Mianwali',
		'Mingora',
		'Mirpur',
		'Mirpur Khas',
		'Multan',
		'Murree',
		'Muzaffarabad',
		'Muzaffargarh',
		'Nankana Sahib ',
		'Naran',
		'Narowal',
		'Nasirabad',
		'Naushahro Feroze',
		'Nawabshah',
		'Neelum',
		'Nowshera',
		'Okara',
		'Pakpattan',
		'Peshawar',
		'Pir Mahal',
		'Quetta',
		'Rahim Yar Khan',
		'Rajanpur',
		'Ratwal',
		'Rawalakot',
		'Rawalpindi',
		'Rohri',
		'Sadiqabad',
		'Sahiwal',
		'Sanghar',
		'Sargodha',
		'Sehwan',
		'Shahdadpur',
		'Sheikhupura',
		'Shikarpur',
		'Sialkot',
		'Sibi',
		'Skardu',
		'Sudhnoti',
		'Sukkur',
		'Swabi',
		'Swat',
		'Tando Adam',
		'Taxila',
		'Thatta',
		'Toba Tek Singh',
		'Vehari',
		'Wah',
		'Wazirabad',
		'Waziristan',
		'Zhob',
    ];

    public static function All(){
        return static::$cities;
    }
}